from clusterspecialists.algorithms.Algorithm import Algorithm
from clusterspecialists.algorithms.perceptron import Perceptron
from clusterspecialists.algorithms.specialists import Specialists
from clusterspecialists.algorithms.naiveheterogeneous import NaiveHeterogeneous
from clusterspecialists.algorithms.notsonaive import NotSoNaive
from clusterspecialists.algorithms.naivehomogeneous import NaiveHomogeneous
from clusterspecialists.algorithms.globaltemporal import GlobalTemporal
